import { FaTable } from "react-icons/fa";
import { MdOutlineSecurity } from "react-icons/md";
import { MdSettingsApplications } from "react-icons/md";
import { IoSettings } from "react-icons/io5";
import { FaFirstOrder } from "react-icons/fa";
import { MdInventory } from "react-icons/md";
import { MdPayments } from "react-icons/md";
import { MdAccountBox } from "react-icons/md";
import { FaFileUpload } from "react-icons/fa";
import { BiSolidReport } from "react-icons/bi";

export const sideBarMenus = [
  {
    id: 1,
    menuName: " Security",
    menuNameBn: "Security",
    icon: MdOutlineSecurity,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 1,
        menuName: "1A0. Store Menu Role Mapping",
        menuNameBn: "1A0. Store Menu Role Mapping",
        routeUrl: "/security/role-mapping",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 2,
        menuName: "1A1. User Registration",
        menuNameBn: "1A1. User Registration",
        routeUrl: "/security/user-registration",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 3,
        menuName: "1A2. Menu Role",
        menuNameBn: "1A2. Menu Role",
        routeUrl: "/security/menu-role",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 4,
        menuName: "1B1. Vms Menus",
        menuNameBn: "1B1. Vms Menus",
        routeUrl: "/security/vms-menus",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 5,
        menuName: "1B2. Menus",
        menuNameBn: "1B2. Menus",
        routeUrl: "/security/menus",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 6,
        menuName: "1B4. Model Permissions",
        menuNameBn: "1B4. Model Permissions",
        routeUrl: "/security/model-permissions",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 7,
        menuName: "1Z. Audit Trails",
        menuNameBn: "1Z. Audit Trails",
        routeUrl: "/security/audit-trails",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
  {
    id: 1,
    menuName: "Application Setting",
    menuNameBn: "Application Setting",
    icon: MdSettingsApplications,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 13,
        menuName: "2A1. VAT Regi Type",
        menuNameBn: "2A1. VAT Regi Type",
        routeUrl: "/hk/vat-reg-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2A2. Economic Activity",
        menuNameBn: "2A2. Economic Activity",
        routeUrl: "/hk/economic-activity",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2A3. Business Information",
        menuNameBn: "2A3. Business Information",
        routeUrl: "/hk/business-information",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2A4. Area Of Economic Activity",
        menuNameBn: "2A4. Area Of Economic Activity",
        routeUrl: "/hk/area-of-economic-activity",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2B. Vat Rebate Type",
        menuNameBn: "2B. Vat Rebate Type",
        routeUrl: "/hk/vat-rebate-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C1. Tran Source Type",
        menuNameBn: "2C1. Tran Source Type",
        routeUrl: "/hk/trans-source-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C2. Transaction Type",
        menuNameBn: "2C2. Transaction Type",
        routeUrl: "/hk/trans-type",
        isNewTap: 0,
        childs: [],
      },

      {
        id: 13,
        menuName: "2C3. Tran Sub Type",
        menuNameBn: "2C3. Tran Sub Type",
        routeUrl: "/hk/trans-sub-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C4. Vat Pay Method",
        menuNameBn: "2C4. Vat Pay Method",
        routeUrl: "/hk/vat-pay-method",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C5. Item Cat For Retail",
        menuNameBn: "2C5. Item Cat For Retail",
        routeUrl: "/hk/item-cat-for-retail",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C6. Vat Rate Ref",
        menuNameBn: "2C6. Vat Rate Ref",
        routeUrl: "/hk/vat-rate-ref",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C7. Vat Rate Type",
        menuNameBn: "2C7. Vat Rate Type",
        routeUrl: "/hk/vat-rate-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2C8. Vat Rate Stage",
        menuNameBn: "2C8. Vat Rate Stage",
        routeUrl: "/hk/vat-rate-stage",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2D1. Product Category",
        menuNameBn: "2D1. Product Category",
        routeUrl: "/hk/prod-cat-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2D2. Product Type",
        menuNameBn: "2D2. Product Type",
        routeUrl: "/hk/product-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2E1. HS Code",
        menuNameBn: "2E1. HS Code",
        routeUrl: "/hk/hs-code",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2E2. Vat Structure",
        menuNameBn: "2E2. Vat Structure",
        routeUrl: "/hk/vat-structure",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2F. UOM & Currency",
        menuNameBn: "2F. UOM & Currency",
        routeUrl: "",
        isNewTap: 0,
        childs: [
          {
            id: 13,
            menuName: "2F1. Uom Set",
            menuNameBn: "2F1. Uom Set",

            routeUrl: "/hk/uom-set",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "2F2. UOM",
            menuNameBn: "2F2. UOM",

            routeUrl: "/hk/uom-info",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "2F3. Currency Info",
            menuNameBn: "2F3. Currency Info",

            routeUrl: "/hk/currency-info",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "2F4. Currency Exc Rate",
            menuNameBn: "2F4. Currency Exc Rate",

            routeUrl: "/hk/currency-exc-rate",
            isNewTap: 0,
            childs: [],
          },
        ],
      },
      {
        id: 13,
        menuName: "2G. Inventory Method",
        menuNameBn: "2G. Inventory Method",
        routeUrl: "/hk/inventory-method",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2H1. Bank Info",
        menuNameBn: "2H1. Bank Info",
        routeUrl: "/hk/bank-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2H2. Bank Branch Info",
        menuNameBn: "2H2. Bank Branch Info",
        routeUrl: "/hk/bank-branch-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2H3. Bank Account Type",
        menuNameBn: "2H3. Bank Account Type",
        routeUrl: "/hk/bank-account-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2J1. Fiscal Year Info",
        menuNameBn: "2J1. Fiscal Year Info",
        routeUrl: "/hk/fiscal-year",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2J2. Vat Month Info",
        menuNameBn: "2J2. Vat Month Info",
        routeUrl: "/hk/vat-month-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2K1. Commission Rate",
        menuNameBn: "2K1. Commission Rate",
        routeUrl: "/hk/commission-rate",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2K2. Acct Code Info",
        menuNameBn: "2K2. Acct Code Info",
        routeUrl: "/hk/account-code",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2K3. Acct Item Info",
        menuNameBn: "2K3. Acct Item Info",
        routeUrl: "/hk/trans-account-item-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2L3. Payment Mode",
        menuNameBn: "2L3. Payment Mode",
        routeUrl: "/hk/payment-mode",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2N1. Debit Note For",
        menuNameBn: "2N1. Debit Note For",
        routeUrl: "/hk/debit-note-for",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2N2. Credit Note For",
        menuNameBn: "2N2. Credit Note For",
        routeUrl: "/hk/credit-note-for",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2P1. Challan Type",
        menuNameBn: "2P1. Challan Type",
        routeUrl: "/hk/challan-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2P2. Vehicle Type",
        menuNameBn: "2P2. Vehicle Type",
        routeUrl: "/hk/vehicle-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2Q1. Others Adjustments",
        menuNameBn: "2Q1. Others Adjustments",
        routeUrl: "/hk/others-adjustments",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2Q2. Others Adjt Type",
        menuNameBn: "2Q2. Others Adjt Type",
        routeUrl: "/hk/other-adjustment-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2Q5. Port Info",
        menuNameBn: "2Q5. Port Info",
        routeUrl: "/hk/port-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R1. Address Type",
        menuNameBn: "2R1. Address Type",
        routeUrl: "/hk/address-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R2. Country",
        menuNameBn: "2R2. Country",
        routeUrl: "/hk/country",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R3. Division",
        menuNameBn: "2R3. Division",
        routeUrl: "/hk/division",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R4. District",
        menuNameBn: "2R4. District",
        routeUrl: "/hk/district",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R5. Upazilla",
        menuNameBn: "2R5. Upazilla",
        routeUrl: "/hk/upazilla",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R6. City",
        menuNameBn: "2R6. City",
        routeUrl: "/hk/city",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R7. Area",
        menuNameBn: "2R7. Area",
        routeUrl: "/hk/area",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R8. Police Station",
        menuNameBn: "2R8. Police Station",
        routeUrl: "/hk/police-station",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R9. Document Type",
        menuNameBn: "2R9. Document Type",
        routeUrl: "/hk/document-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2R10. Company Type",
        menuNameBn: "2R10. Company Type",
        routeUrl: "/hk/company-type",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2S1. Language",
        menuNameBn: "2S1. Language",
        routeUrl: "/hk/language",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2T1. LC For",
        menuNameBn: "2T1. LC For",
        routeUrl: "/hk/lc-for",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "2T2. Import LC Purpose",
        menuNameBn: "2T2.Import LC Purposer",
        routeUrl: "/hk/import-lc-purpose",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
  {
    id: 13,
    menuName: "Company Setting",
    menuNameBn: "Company Setting",
    icon: IoSettings,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 13,
        menuName: "3A. Company Details",
        menuNameBn: "3A. Company Details",
        routeUrl: "/company-setting/company-Info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3B. Company Branch",
        menuNameBn: "3B. Company Branch",
        routeUrl: "/company-setting/company-branch",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3C. Company Store",
        menuNameBn: "3C. Company Store",
        routeUrl: "",
        isNewTap: 0,
        childs: [
          {
            id: 13,
            menuName: "3C1. Store Details",
            menuNameBn: "3C1. Store Details",

            routeUrl: "/company-setting/company-store/store-location",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "3C6. Store User Mapping",
            menuNameBn: "3C6. Store User Mapping",

            routeUrl: "/company-setting/company-store/store-user-mapping",
            isNewTap: 0,
            childs: [],
          },
        ],
      },
      {
        id: 13,
        menuName: "3D. Company Department",
        menuNameBn: "3D. Company Department",
        routeUrl: "/company-setting/department",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3E. Company Designation",
        menuNameBn: "3E. Company Designation",
        routeUrl: "/company-setting/designation",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3F. Company Section",
        menuNameBn: "3F. Company Section",
        routeUrl: "/company-setting/section",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3G. Company Sub Section",
        menuNameBn: "3G. Company Sub Section",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3H. Company Employee",
        menuNameBn: "3H. Company Employee",
        routeUrl: "/company-setting/employee",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3J. Customer Setup",
        menuNameBn: "3J. Customer Setup",
        routeUrl: "/company-setting/customer-setup",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3K. Supplier Setup",
        menuNameBn: "3K. Supplier Setup",
        routeUrl: "/company-setting/supplier-info",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3N. Items",
        menuNameBn: "3N. Items",
        routeUrl: "",
        isNewTap: 0,
        childs: [
          {
            id: 13,
            menuName: "3N01. Item Master Group",
            menuNameBn: "3N01. Item Master Group",

            routeUrl: "/company-setting/items/master-group",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "3N02. Item Group",
            menuNameBn: "3N02. Item Group",

            routeUrl: "/company-setting/items/item-group",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "3N03. Item Sub Group",
            menuNameBn: "3N03. Item Sub Group",

            routeUrl: "/company-setting/items/item-sub-group",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "3N05. Item Details",
            menuNameBn: "3N05. Item Details",

            routeUrl: "/company-setting/items/item-info",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "3N09. Item Store Mapping",
            menuNameBn: "3N09. Item Store Mapping",

            routeUrl: "/company-setting/items/item-store-mapping",
            isNewTap: 0,
            childs: [],
          },
        ],
      },
      {
        id: 13,
        menuName: "3R. Legal Documents Status",
        menuNameBn: "3R. Legal Documents Status",
        routeUrl: "/company-setting/legal-documents",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3T. Company Config Info",
        menuNameBn: "3T. Company Config Info",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3U. Price Decleartion",
        menuNameBn: "3U. Price Decleartion",
        routeUrl: "",
        isNewTap: 0,
        childs: [
          {
            id: 13,
            menuName: "3U1. Price Determination",
            menuNameBn: "3U1. Price Determination",

            routeUrl: "/company-setting/price-determination",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "3U2. Price Declar Approval",
            menuNameBn: "3U2. Price Declar Approval",

            routeUrl: "",
            isNewTap: 0,
            childs: [],
          },
        ],
      },
      {
        id: 13,
        menuName: "3V. Commission Histories",
        menuNameBn: "3V. Commission Histories",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3X1. Vms Monthly Closing Pro",
        menuNameBn: "3X1. Vms Monthly Closing Pro",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "3X2. Vms Pk Serial",
        menuNameBn: "3X2. Vms Pk Serial",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
  {
    id: 13,
    menuName: "Order Management",
    menuNameBn: "Order Management",
    icon: FaFirstOrder,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 13,
        menuName: "4E. Export LC",
        menuNameBn: "4E. Export LC",
        routeUrl: "/order-management/export-lc",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "4F.Utilization Declaration(UD)",
        menuNameBn: "4F.Utilization Declaration(UD)",
        routeUrl: "/order-management/utilize-declare",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "4J. Import LC",
        menuNameBn: "4J. Import LC",
        routeUrl: "/order-management/import-lc",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
  {
    id: 2,
    menuName: "Inventory",
    menuNameBn: "Inventory",
    icon: MdInventory,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 13,
        menuName: "5A. Opening Balance",
        menuNameBn: "5A. Opening Balance",
        routeUrl: "/opening-balance",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5C. Receive",
        menuNameBn: "5C. Receive",
        routeUrl: "",
        isNewTap: 0,
        childs: [
          {
            id: 13,
            menuName: "5C1. Local Purchase",
            menuNameBn: "5C1. Local Purchase",

            routeUrl: "/receive",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5C4. By Bond/LC/Import",
            menuNameBn: "5C4. By Bond/LC/Import",

            routeUrl: "/import_5C4",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5C5. Service Purchase Entry",
            menuNameBn: "5C5. Service Purchase Entry",

            routeUrl: "/hk/service_entry",
            isNewTap: 0,
            childs: [],
          },
        ],
      },
      {
        id: 13,
        menuName: "5D. Debit Note(Purchase Return)",
        menuNameBn: "5D. Debit Note(Purchase Return)",
        routeUrl: "/debit_notes",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5E. Transfer Out",
        menuNameBn: "5E. Transfer Out",
        routeUrl: "/transfer-out",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5F. Transfer IN",
        menuNameBn: "5F. Transfer IN",
        routeUrl: "/transferIn",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5H. Issue to Production",
        menuNameBn: "5H. Issue to Production",
        routeUrl: "/issue-to-production",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5J. Receive From Production",
        menuNameBn: "5J. Receive From Production",
        routeUrl: "/receive-form-production",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5K. Sell-6.3",
        menuNameBn: "5J. Sell-6.3",
        routeUrl: "",
        isNewTap: 0,
        childs: [
          {
            id: 13,
            menuName: "5K1. Local Sells",
            menuNameBn: "5K1. Local Sells",

            routeUrl: "/local_sells",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5K2. Export",
            menuNameBn: "5K2. Export",

            routeUrl: "/export",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5K3. POS/6.3",
            menuNameBn: "5K3. POS/6.3",

            routeUrl: "/hk/pos",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5K4. EMI Sells",
            menuNameBn: "5K4. EMI Sells",

            routeUrl: "/emi",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5K5. Deemed Export",
            menuNameBn: "5K5. Deemed Export",

            routeUrl: "/hk/deemed-export",
            isNewTap: 0,
            childs: [],
          },
          {
            id: 13,
            menuName: "5K6. Service Sells Entry",
            menuNameBn: "5K6. Service Sells Entry",

            routeUrl: "/service_entry",
            isNewTap: 0,
            childs: [],
          },
        ],
      },
      {
        id: 13,
        menuName: "5L. Credit Note(Sell Return)",
        menuNameBn: "5L. Credit Note(Sell Return)",
        routeUrl: "/creadit_notes",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5M. Delivery To Customer",
        menuNameBn: "5M. Delivery To Customer",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5N1. Wastage Manag Raw Mat",
        menuNameBn: "5N1. Wastage Manag Raw Mat",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "5N2. Damaged Finis Goods Manag",
        menuNameBn: "5N2. Damaged Finis Goods Manag",
        routeUrl: "",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
  {
    id: 13,
    menuName: "Commercial",
    menuNameBn: "Commercial",
    icon: MdPayments,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 13,
        menuName: "6D. VDS Purchaser",
        menuNameBn: "6D. VDS Purchaser",
        routeUrl: "/commercial/vds-for-purchaser",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "6E. VDS Seller",
        menuNameBn: "6E. VDS Seller",
        routeUrl: "/commercial/vds-for-seller",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "6F. VDS Payment",
        menuNameBn: "6F. VDS Payment",
        routeUrl: "/commercial/vds-payment",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "6J. Treasury Challan",
        menuNameBn: "6J. Treasury Challan",
        routeUrl: "/commercial/treasury-challan",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "6K. Due Penalty Surcharge",
        menuNameBn: "6K. Due Penalty Surcharge",
        routeUrl: "/commercial/due-penalty-surcharge",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "6L1. Last Month Clo Blance",
        menuNameBn: "6L1. Last Month Clo Blance",
        routeUrl: "/commercial/last-month-closing-balance",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "6M. Others Adjustments",
        menuNameBn: "6M. Other Adjustment",
        routeUrl: "/commercial/others-adjustment",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
  {
    id: 13,
    menuName: "Accounts",
    menuNameBn: "Accounts",
    icon: MdAccountBox,
    routeUrl: "",
    isNewTap: 0,
    childs: [],
  },
  {
    id: 13,
    menuName: "Integration and Upload",
    menuNameBn: "Integration and Upload",
    icon: FaFileUpload,
    routeUrl: "",
    isNewTap: 0,
    childs: [],
  },
  {
    id: 13,
    menuName: "Mushak Reports",
    menuNameBn: "Mushak Reports",
    icon: BiSolidReport,
    routeUrl: "",
    isNewTap: 0,
    childs: [
      {
        id: 13,
        menuName: "9A. Mushak-4.3",
        menuNameBn: "9A. Mushak-4.3",
        routeUrl: "/report/mushak-4.3",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9A1. Mushak-4.4",
        menuNameBn: "9A1. Mushak-4.4",
        routeUrl: "/report/mushak-4.4",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9A2. Mushak-4.5",
        menuNameBn: "9A2. Mushak-4.5",
        routeUrl: "/report/mushak-4.5",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9B. Mushak-6.1",
        menuNameBn: "9B. Mushak-6.1",
        routeUrl: "/report/mushak-6.1",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9C. Mushak-6.2",
        menuNameBn: "9C. Mushak-6.2",
        routeUrl: "/report/mushak-6.2",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9D1. Mushak-6.2.1(Monthwise)",
        menuNameBn: "9D1. Mushak-6.2.1(Monthwise)",
        routeUrl: "/report/mushak-6.2.1-month",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9D2. Mushak-6.2.1(Hubwise)",
        menuNameBn: "9D2. Mushak-6.2.1(Hubwise)",
        routeUrl: "/report/mushak-6.2.1-hub",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9D3. Mushak-6.2.1(Itemwise)",
        menuNameBn: "9D3. Mushak-6.2.1(Itemwise)",
        routeUrl: "/report/mushak-6.2.1-item",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9E. Mushak-6.3",
        menuNameBn: "9E. Mushak-6.3",
        routeUrl: "/report/mushak-6.3",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9F. Mushak-6.5",
        menuNameBn: "9F. Mushak-6.5",
        routeUrl: "/report/mushak-6.5",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9G. Mushak-6.6",
        menuNameBn: "9G. Mushak-6.6",
        routeUrl: "/report/mushak-6.6",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9H. Mushak-6.7",
        menuNameBn: "9H. Mushak-6.7",
        routeUrl: "/report/mushak-6.7",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9I. Mushak-6.8",
        menuNameBn: "9I. Mushak-6.8",
        routeUrl: "/report/mushak-6.8",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9J. Mushak-6.10",
        menuNameBn: "9J. Mushak-6.10",
        routeUrl: "/report/mushak-6.10",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9K. Mushak-9.1",
        menuNameBn: "9K. Mushak-9.1",
        routeUrl: "/report/mushak-9.1",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9L. Chak KA",
        menuNameBn: "9L. Chak KA",
        routeUrl: "/report/chak-ka",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9M. Chak KHA",
        menuNameBn: "9M. Chak KHA",
        routeUrl: "/report/chak-kha",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9Z01. Item Consumption Report",
        menuNameBn: "9Z01. Item Consumption Report",
        routeUrl: "/report/item-cons-report",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9Z01. Finis Goods Con Repo",
        menuNameBn: "9Z01. Finis Goods Con Repo",
        routeUrl: "/report/finis-goods-con-repo",
        isNewTap: 0,
        childs: [],
      },
      {
        id: 13,
        menuName: "9Z01. List Of VDS Not Done",
        menuNameBn: "9Z01. List Of VDS Not Done",
        routeUrl: "/report/list-of-vds-not-done",
        isNewTap: 0,
        childs: [],
      },
    ],
  },
];
